"use strict";

module.exports = {
  game: "t7",
  sources: [
    "http://rbnorway.org/t7-frame-data/akuma-t7-frames",
    "http://rbnorway.org/t7-frame-data/alisa-t7-frames",
    "http://rbnorway.org/t7-frame-data/anna-t7-frames",
    "http://rbnorway.org/t7-frame-data/lei-t7-frames",
    "http://rbnorway.org/t7-frame-data/asuka-t7-frames",
    "http://rbnorway.org/t7-frame-data/bob-t7-frames",
    "http://rbnorway.org/t7-frame-data/bryan-t7-frames",
    "http://rbnorway.org/t7-frame-data/claudio-t7-frames",
    "http://rbnorway.org/T7-frame-data/devil-jin-t7-frames",
    "http://rbnorway.org/T7-frame-data/dragunov-t7-frames",
    "http://rbnorway.org/T7-frame-data/eddy-t7-frames/",
    "http://rbnorway.org/T7-frame-data/eliza-t7-frames/",
    "http://rbnorway.org/T7-frame-data/feng-t7-frames",
    "http://rbnorway.org/T7-frame-data/geese-t7-frames",
    "http://rbnorway.org/T7-frame-data/gigas-t7-frames",
    "http://rbnorway.org/T7-frame-data/heihachi-t7-frames",
    "http://rbnorway.org/T7-frame-data/Hwoarang-t7-frames",
    "http://rbnorway.org/T7-frame-data/jack7-t7-frames",
    "http://rbnorway.org/jin-t7-frames/",
    "http://rbnorway.org/josie-t7-frames/",
    "http://rbnorway.org/T7-frame-data/katarina-t7-frames",
    "http://rbnorway.org/T7-frame-data/kazumi-t7-frames",
    "http://rbnorway.org/T7-frame-data/kazuya-t7-frames",
    "http://rbnorway.org/T7-frame-data/king-t7-frames",
    "http://rbnorway.org/T7-frame-data/kuma-t7-frames",
    "http://rbnorway.org/T7-frame-data/lars-t7-frames",
    "http://rbnorway.org/law-t7-frames/",
    "http://rbnorway.org/T7-frame-data/lee-t7-frames",
    "http://rbnorway.org/T7-frame-data/leo-t7-frames",
    "http://rbnorway.org/T7-frame-data/lili-t7-frames",
    "http://rbnorway.org/T7-frame-data/lucky-chloe-t7-frames",
    "http://rbnorway.org/T7-frame-data/master-raven-t7-frames/",
    "http://rbnorway.org/T7-frame-data/miguel-t7-frames",
    "http://rbnorway.org/T7-frame-data/nina-t7-frames",
    "http://rbnorway.org/T7-frame-data/Noctis-t7-frames",
    "http://rbnorway.org/T7-frame-data/paul-t7-frames",
    "http://rbnorway.org/T7-frame-data/shaheen-t7-frames",
    "http://rbnorway.org/T7-frame-data/steve-t7-frames",
    "http://rbnorway.org/T7-frame-data/xiaoyu-t7-frames",
    "http://rbnorway.org/yoshimitsu-t7-frames/"
  ],
  limit: 5,
  ver: "0.4"
};
