"use strict";

module.exports = {
  game: "ttt2",
  sources: [
    "http://rbnorway.org/ttt2-frame-data/alex-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/ttt2-frame-data-alisa",
    "http://rbnorway.org/ttt2-frame-data/ancient-ogre",
    "http://rbnorway.org/ttt2-frame-data/angel-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/anna-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/armor-king-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/ttt2-asuka-frames",
    "http://rbnorway.org/ttt2-frame-data/baek-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/bob-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/bruce-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/bryan-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/eddy-ttt2u-frames",
    "http://rbnorway.org/ttt2-frame-data/marduk-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/devil-jin-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/dr-b-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/dragunov-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/eddy-ttt2u-frames",
    "http://rbnorway.org/ttt2-frame-data/feng-ttt2u-frames",
    "http://rbnorway.org/ttt2-frame-data/ganryu-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/forest-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/heihachi-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/hwoarang-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/jack6-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/jaycee-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/jin-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/jinpachi-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/jun-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/kazuya-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/king-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/kuma-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/kunimitsu-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/lars-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/lee-ttt2u-frames",
    "http://rbnorway.org/ttt2-frame-data/lei-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/leo-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/lili-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/xiaoyu-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/marshall-law-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/michelle-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/miharu-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/ttt2-miguel-frame-data",
    "http://rbnorway.org/ttt2-frame-data/nina-ttt2-frame-data",
    "http://rbnorway.org/ttt2-frame-data/ogre",
    "http://rbnorway.org/ttt2-frame-data/paul-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/p-jack-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/raven-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/rogerjr-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/sebastian-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/slim-bob-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/steve-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/tiger-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/unknown-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/violet-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/wang-ttt2u-frames",
    "http://rbnorway.org/ttt2-frame-data/yoshimitsu-ttt2-frames",
    "http://rbnorway.org/ttt2-frame-data/zafina-ttt2-frames"
  ],
  limit: 5,
  ver: "0.4"
};
